#!/usr/bin/env bash
# ── Valor Assist — AWS Deploy Script ─────────────────────────────────
# Builds Docker images from the valor-assist-final branch, pushes them
# to ECR, registers ECS task definitions, and deploys/updates services.
#
# Prerequisites:
#   - AWS CLI v2 installed and configured
#   - Docker installed and running
#   - Infrastructure provisioned via ./scripts/setup_aws_infrastructure.sh
#   - scripts/aws_config.env filled in
#   - scripts/aws_resources.env generated by setup script
#
# Usage:
#   chmod +x scripts/deploy_aws.sh
#   ./scripts/deploy_aws.sh [--skip-build] [--backend-only] [--frontend-only]
#
# Options:
#   --skip-build      Skip Docker build, only update ECS services
#   --backend-only    Deploy backend only
#   --frontend-only   Deploy frontend only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/aws_config.env"
RESOURCES_FILE="${SCRIPT_DIR}/aws_resources.env"

# ── Parse arguments ──────────────────────────────────────────────────
SKIP_BUILD=false
DEPLOY_BACKEND=true
DEPLOY_FRONTEND=true

for arg in "$@"; do
    case "$arg" in
        --skip-build)    SKIP_BUILD=true ;;
        --backend-only)  DEPLOY_FRONTEND=false ;;
        --frontend-only) DEPLOY_BACKEND=false ;;
        --help|-h)
            echo "Usage: $0 [--skip-build] [--backend-only] [--frontend-only]"
            exit 0 ;;
        *)
            echo "Unknown option: $arg"
            exit 1 ;;
    esac
done

# ── Load configuration ───────────────────────────────────────────────
for f in "$CONFIG_FILE" "$RESOURCES_FILE"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Required file not found: $f"
        if [[ "$f" == "$RESOURCES_FILE" ]]; then
            echo "Run ./scripts/setup_aws_infrastructure.sh first."
        else
            echo "Copy scripts/aws_config.env.example → scripts/aws_config.env and fill in values."
        fi
        exit 1
    fi
    # shellcheck source=/dev/null
    source "$f"
done

ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
IMAGE_TAG="$(git rev-parse --short HEAD 2>/dev/null || echo 'latest')"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Valor Assist — AWS Deployment                              ║"
echo "║  Region: ${AWS_REGION}                                      ║"
echo "║  Cluster: ${ECS_CLUSTER_NAME}                               ║"
echo "║  Image tag: ${IMAGE_TAG}                                    ║"
echo "║  Timestamp: ${TIMESTAMP}                                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"

# ── Authenticate Docker to ECR ────────────────────────────────────────
echo ""
echo "── Authenticating Docker to ECR ──"
aws ecr get-login-password --region "$AWS_REGION" | \
    docker login --username AWS --password-stdin "$ECR_REGISTRY"
echo "  ✓ Docker authenticated to ECR"

# ── Build and push images ─────────────────────────────────────────────
if [[ "$SKIP_BUILD" == "false" ]]; then

    if [[ "$DEPLOY_BACKEND" == "true" ]]; then
        echo ""
        echo "── Building backend Docker image ──"
        BACKEND_IMAGE="${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}"

        docker build \
            -t "${BACKEND_IMAGE}:${IMAGE_TAG}" \
            -t "${BACKEND_IMAGE}:latest" \
            -f "${PROJECT_ROOT}/Dockerfile" \
            "${PROJECT_ROOT}"
        echo "  ✓ Built backend image: ${BACKEND_IMAGE}:${IMAGE_TAG}"

        echo "── Pushing backend image to ECR ──"
        docker push "${BACKEND_IMAGE}:${IMAGE_TAG}"
        docker push "${BACKEND_IMAGE}:latest"
        echo "  ✓ Pushed backend image to ECR"
    fi

    if [[ "$DEPLOY_FRONTEND" == "true" ]]; then
        echo ""
        echo "── Building frontend Docker image ──"
        FRONTEND_IMAGE="${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}"

        docker build \
            -t "${FRONTEND_IMAGE}:${IMAGE_TAG}" \
            -t "${FRONTEND_IMAGE}:latest" \
            -f "${PROJECT_ROOT}/frontend/Dockerfile" \
            "${PROJECT_ROOT}/frontend"
        echo "  ✓ Built frontend image: ${FRONTEND_IMAGE}:${IMAGE_TAG}"

        echo "── Pushing frontend image to ECR ──"
        docker push "${FRONTEND_IMAGE}:${IMAGE_TAG}"
        docker push "${FRONTEND_IMAGE}:latest"
        echo "  ✓ Pushed frontend image to ECR"
    fi
else
    echo ""
    echo "── Skipping Docker build (--skip-build) ──"
fi

# ── Register ECS Task Definitions ─────────────────────────────────────
if [[ "$DEPLOY_BACKEND" == "true" ]]; then
    echo ""
    echo "── Registering backend task definition ──"

    BACKEND_TASK_DEF=$(cat <<EOF
{
    "family": "${ECS_BACKEND_TASK_FAMILY}",
    "networkMode": "awsvpc",
    "requiresCompatibilities": ["FARGATE"],
    "cpu": "${BACKEND_CPU}",
    "memory": "${BACKEND_MEMORY}",
    "executionRoleArn": "${EXEC_ROLE_ARN}",
    "taskRoleArn": "${TASK_ROLE_ARN}",
    "containerDefinitions": [{
        "name": "valor-assist-backend",
        "image": "${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${IMAGE_TAG}",
        "essential": true,
        "portMappings": [{
            "containerPort": 8000,
            "protocol": "tcp"
        }],
        "environment": [
            {"name": "EMBEDDING_PROVIDER", "value": "voyageai"},
            {"name": "ALLOWED_ORIGINS", "value": "[\"*\"]"},
            {"name": "ENABLE_HSTS", "value": "true"},
            {"name": "RATE_LIMIT_MAX_REQUESTS", "value": "30"},
            {"name": "SESSION_TTL_SECONDS", "value": "3600"}
        ],
        "secrets": [
            {"name": "ANTHROPIC_API_KEY", "valueFrom": "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${SECRET_NAME}:ANTHROPIC_API_KEY::"},
            {"name": "VOYAGE_API_KEY", "valueFrom": "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${SECRET_NAME}:VOYAGE_API_KEY::"},
            {"name": "ENCRYPTION_KEY", "valueFrom": "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${SECRET_NAME}:ENCRYPTION_KEY::"},
            {"name": "JWT_SECRET_KEY", "valueFrom": "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_ID}:secret:${SECRET_NAME}:JWT_SECRET_KEY::"}
        ],
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-group": "/ecs/valor-assist-backend",
                "awslogs-region": "${AWS_REGION}",
                "awslogs-stream-prefix": "ecs"
            }
        },
        "healthCheck": {
            "command": ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\" || exit 1"],
            "interval": 30,
            "timeout": 5,
            "retries": 3,
            "startPeriod": 10
        }
    }]
}
EOF
    )

    echo "$BACKEND_TASK_DEF" > /tmp/backend-task-def.json
    aws ecs register-task-definition \
        --cli-input-json file:///tmp/backend-task-def.json \
        --region "$AWS_REGION" >/dev/null
    rm -f /tmp/backend-task-def.json
    echo "  ✓ Registered backend task definition: ${ECS_BACKEND_TASK_FAMILY}"
fi

if [[ "$DEPLOY_FRONTEND" == "true" ]]; then
    echo ""
    echo "── Registering frontend task definition ──"

    FRONTEND_TASK_DEF=$(cat <<EOF
{
    "family": "${ECS_FRONTEND_TASK_FAMILY}",
    "networkMode": "awsvpc",
    "requiresCompatibilities": ["FARGATE"],
    "cpu": "${FRONTEND_CPU}",
    "memory": "${FRONTEND_MEMORY}",
    "executionRoleArn": "${EXEC_ROLE_ARN}",
    "containerDefinitions": [{
        "name": "valor-assist-frontend",
        "image": "${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${IMAGE_TAG}",
        "essential": true,
        "portMappings": [{
            "containerPort": 80,
            "protocol": "tcp"
        }],
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-group": "/ecs/valor-assist-frontend",
                "awslogs-region": "${AWS_REGION}",
                "awslogs-stream-prefix": "ecs"
            }
        },
        "healthCheck": {
            "command": ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"],
            "interval": 30,
            "timeout": 5,
            "retries": 3,
            "startPeriod": 10
        }
    }]
}
EOF
    )

    echo "$FRONTEND_TASK_DEF" > /tmp/frontend-task-def.json
    aws ecs register-task-definition \
        --cli-input-json file:///tmp/frontend-task-def.json \
        --region "$AWS_REGION" >/dev/null
    rm -f /tmp/frontend-task-def.json
    echo "  ✓ Registered frontend task definition: ${ECS_FRONTEND_TASK_FAMILY}"
fi

# ── Create or Update ECS Services ─────────────────────────────────────
create_or_update_service() {
    local service_name="$1"
    local task_family="$2"
    local target_group="$3"
    local container_name="$4"
    local container_port="$5"
    local desired_count="$6"

    if aws ecs describe-services --cluster "$ECS_CLUSTER_NAME" --services "$service_name" --region "$AWS_REGION" \
        --query 'services[?status==`ACTIVE`].serviceName' --output text 2>/dev/null | grep -q "$service_name"; then
        echo "  Updating existing service: $service_name"
        aws ecs update-service \
            --cluster "$ECS_CLUSTER_NAME" \
            --service "$service_name" \
            --task-definition "$task_family" \
            --desired-count "$desired_count" \
            --force-new-deployment \
            --region "$AWS_REGION" >/dev/null
    else
        echo "  Creating new service: $service_name"
        aws ecs create-service \
            --cluster "$ECS_CLUSTER_NAME" \
            --service-name "$service_name" \
            --task-definition "$task_family" \
            --desired-count "$desired_count" \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[${PRIV_SUBNET_1},${PRIV_SUBNET_2}],securityGroups=[${ECS_SG}],assignPublicIp=DISABLED}" \
            --load-balancers "targetGroupArn=${target_group},containerName=${container_name},containerPort=${container_port}" \
            --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100" \
            --region "$AWS_REGION" \
            --tags key=Project,value="${PROJECT_TAG}" key=Environment,value="${ENVIRONMENT_TAG}" \
            >/dev/null
    fi
    echo "  ✓ Service $service_name deployed"
}

if [[ "$DEPLOY_BACKEND" == "true" ]]; then
    echo ""
    echo "── Deploying backend service ──"
    create_or_update_service \
        "$ECS_BACKEND_SERVICE" \
        "$ECS_BACKEND_TASK_FAMILY" \
        "$BACKEND_TG" \
        "valor-assist-backend" \
        8000 \
        "$BACKEND_DESIRED_COUNT"
fi

if [[ "$DEPLOY_FRONTEND" == "true" ]]; then
    echo ""
    echo "── Deploying frontend service ──"
    create_or_update_service \
        "$ECS_FRONTEND_SERVICE" \
        "$ECS_FRONTEND_TASK_FAMILY" \
        "$FRONTEND_TG" \
        "valor-assist-frontend" \
        80 \
        "$FRONTEND_DESIRED_COUNT"
fi

# ── Wait for services to stabilize ────────────────────────────────────
echo ""
echo "── Waiting for services to stabilize ──"

WAIT_SERVICES=""
if [[ "$DEPLOY_BACKEND" == "true" ]]; then
    WAIT_SERVICES="$ECS_BACKEND_SERVICE"
fi
if [[ "$DEPLOY_FRONTEND" == "true" ]]; then
    WAIT_SERVICES="${WAIT_SERVICES:+$WAIT_SERVICES }$ECS_FRONTEND_SERVICE"
fi

if [[ -n "$WAIT_SERVICES" ]]; then
    # shellcheck disable=SC2086
    aws ecs wait services-stable \
        --cluster "$ECS_CLUSTER_NAME" \
        --services $WAIT_SERVICES \
        --region "$AWS_REGION" 2>/dev/null || echo "  ⚠ Timed out waiting — check ECS console for status"
    echo "  ✓ Services stabilized"
fi

# ── Summary ───────────────────────────────────────────────────────────
ALB_DNS=$(aws elbv2 describe-load-balancers --names valor-assist-alb --region "$AWS_REGION" \
    --query 'LoadBalancers[0].DNSName' --output text 2>/dev/null || echo "N/A")

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Deployment complete!                                       ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  ALB URL:   http://${ALB_DNS}"
echo "║  Backend:   http://${ALB_DNS}/api/health"
echo "║  Frontend:  http://${ALB_DNS}/"
echo "║  Image tag: ${IMAGE_TAG}"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  View logs:                                                 ║"
echo "║    aws logs tail /ecs/valor-assist-backend --follow          ║"
echo "║    aws logs tail /ecs/valor-assist-frontend --follow         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
